### DISCUSSION TITLE
Use this tool in Github action

### DISCUSSION THREAD

**Discussion by chenxizhang** [chenxizhang/openai-powershell#247] [Use cases]
You can use the tool in Github action for the automation scenario. Below is an example for translate scenario.

```yml
name: test
on: push

jobs:
  gpt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: changed-files
        name: changed-files
        uses: knu/changed-files@v1.0.0
        with:
            paths: "docs/zh/*.md"
      - name: translate
        shell: pwsh
        env:
            files: ${{steps.changed-files.outputs.matched_files_json}}
            system: "You help me translate the content to English"
            openai_api_key: ${{secrets.OPENAI_API_KEY}}
        run: |
            Set-PSRepository -InstallationPolicy Trusted -Name PSGallery
            Install-Module -Name code365scripts.openai -RequiredVersion 2.0.2.2
            Import-Module code365scripts.openai
            $env:files | ConvertFrom-Json | ForEach-Object { 
                $file = $_ -replace "zh", "en";
                gpt -system $env:system -prompt $_ -api_key $env:openai_api_key -OutFile $file
            }
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
 
```
